// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// dksum
NumericVector dksum(NumericVector x, NumericVector p, NumericVector y, int n, int m, double h);
RcppExport SEXP _NBrotate_dksum(SEXP xSEXP, SEXP pSEXP, SEXP ySEXP, SEXP nSEXP, SEXP mSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(dksum(x, p, y, n, m, h));
    return rcpp_result_gen;
END_RCPP
}
// den_fast
NumericVector den_fast(NumericVector x, NumericVector p, int n, int m, double h);
RcppExport SEXP _NBrotate_den_fast(SEXP xSEXP, SEXP pSEXP, SEXP nSEXP, SEXP mSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(den_fast(x, p, n, m, h));
    return rcpp_result_gen;
END_RCPP
}
// den_fast_all
NumericVector den_fast_all(NumericVector x, IntegerVector y, int n, IntegerVector ns, int nc, int maxn, NumericVector hs);
RcppExport SEXP _NBrotate_den_fast_all(SEXP xSEXP, SEXP ySEXP, SEXP nSEXP, SEXP nsSEXP, SEXP ncSEXP, SEXP maxnSEXP, SEXP hsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ns(nsSEXP);
    Rcpp::traits::input_parameter< int >::type nc(ncSEXP);
    Rcpp::traits::input_parameter< int >::type maxn(maxnSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type hs(hsSEXP);
    rcpp_result_gen = Rcpp::wrap(den_fast_all(x, y, n, ns, nc, maxn, hs));
    return rcpp_result_gen;
END_RCPP
}
// dksum_cross
NumericMatrix dksum_cross(NumericVector x, NumericMatrix w, IntegerVector y, int n, IntegerVector ns, int nc, int maxn, NumericVector hs);
RcppExport SEXP _NBrotate_dksum_cross(SEXP xSEXP, SEXP wSEXP, SEXP ySEXP, SEXP nSEXP, SEXP nsSEXP, SEXP ncSEXP, SEXP maxnSEXP, SEXP hsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type w(wSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ns(nsSEXP);
    Rcpp::traits::input_parameter< int >::type nc(ncSEXP);
    Rcpp::traits::input_parameter< int >::type maxn(maxnSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type hs(hsSEXP);
    rcpp_result_gen = Rcpp::wrap(dksum_cross(x, w, y, n, ns, nc, maxn, hs));
    return rcpp_result_gen;
END_RCPP
}
// dksum_all
NumericVector dksum_all(NumericVector x, NumericMatrix w, IntegerVector y, int n, int nc, NumericVector hs);
RcppExport SEXP _NBrotate_dksum_all(SEXP xSEXP, SEXP wSEXP, SEXP ySEXP, SEXP nSEXP, SEXP ncSEXP, SEXP hsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type w(wSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type nc(ncSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type hs(hsSEXP);
    rcpp_result_gen = Rcpp::wrap(dksum_all(x, w, y, n, nc, hs));
    return rcpp_result_gen;
END_RCPP
}
// dksum_all_in_class
NumericVector dksum_all_in_class(NumericVector x, NumericMatrix w, IntegerVector y, int n, IntegerVector ns, int nc, int maxn, NumericVector hs);
RcppExport SEXP _NBrotate_dksum_all_in_class(SEXP xSEXP, SEXP wSEXP, SEXP ySEXP, SEXP nSEXP, SEXP nsSEXP, SEXP ncSEXP, SEXP maxnSEXP, SEXP hsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type w(wSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ns(nsSEXP);
    Rcpp::traits::input_parameter< int >::type nc(ncSEXP);
    Rcpp::traits::input_parameter< int >::type maxn(maxnSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type hs(hsSEXP);
    rcpp_result_gen = Rcpp::wrap(dksum_all_in_class(x, w, y, n, ns, nc, maxn, hs));
    return rcpp_result_gen;
END_RCPP
}
// den_fast_no_loo
NumericVector den_fast_no_loo(NumericVector x, NumericVector p, int n, int m, double h);
RcppExport SEXP _NBrotate_den_fast_no_loo(SEXP xSEXP, SEXP pSEXP, SEXP nSEXP, SEXP mSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(den_fast_no_loo(x, p, n, m, h));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_NBrotate_dksum", (DL_FUNC) &_NBrotate_dksum, 6},
    {"_NBrotate_den_fast", (DL_FUNC) &_NBrotate_den_fast, 5},
    {"_NBrotate_den_fast_all", (DL_FUNC) &_NBrotate_den_fast_all, 7},
    {"_NBrotate_dksum_cross", (DL_FUNC) &_NBrotate_dksum_cross, 8},
    {"_NBrotate_dksum_all", (DL_FUNC) &_NBrotate_dksum_all, 6},
    {"_NBrotate_dksum_all_in_class", (DL_FUNC) &_NBrotate_dksum_all_in_class, 8},
    {"_NBrotate_den_fast_no_loo", (DL_FUNC) &_NBrotate_den_fast_no_loo, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_NBrotate(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
