# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dksum <- function(x, p, y, n, m, h) {
    .Call(`_NBrotate_dksum`, x, p, y, n, m, h)
}

den_fast <- function(x, p, n, m, h) {
    .Call(`_NBrotate_den_fast`, x, p, n, m, h)
}

den_fast_all <- function(x, y, n, ns, nc, maxn, hs) {
    .Call(`_NBrotate_den_fast_all`, x, y, n, ns, nc, maxn, hs)
}

dksum_cross <- function(x, w, y, n, ns, nc, maxn, hs) {
    .Call(`_NBrotate_dksum_cross`, x, w, y, n, ns, nc, maxn, hs)
}

dksum_all <- function(x, w, y, n, nc, hs) {
    .Call(`_NBrotate_dksum_all`, x, w, y, n, nc, hs)
}

dksum_all_in_class <- function(x, w, y, n, ns, nc, maxn, hs) {
    .Call(`_NBrotate_dksum_all_in_class`, x, w, y, n, ns, nc, maxn, hs)
}

den_fast_no_loo <- function(x, p, n, m, h) {
    .Call(`_NBrotate_den_fast_no_loo`, x, p, n, m, h)
}

